### PR TITLE
Pre-compile templates

### LINKED ISSUE #1: Add precompile
It would be awesome if MSX had the ability to precompile the templates.

### PR DESCRIPTION
**Pull request by liamcurry**
These changes [pre-compile Mithril templates for extra performance](http://lhorie.github.io/mithril/optimizing-performance.html).

All tests pass and the TODO example still works.

Fixes #1.

### CODE REVIEW

**Comment by insin** [comment]
One thing I'm wondering, having not looked at Mithril for a while (waiting for some sort of componentisation story to land as a core feature) I see there's now [Mithril.Elements](https://github.com/philtoms/mithril.elements) which hijacks `m()` calls to implement custom element types - should we keep the `m()` calls for unrecognised tag names to allow people to use MSX with that?

**Comment by liamcurry** [comment]
I've never used Mithril.Elements, but I guess it couldn't hurt to leave `m()` as an option.

**Comment by insin** [comment]
These changes have been committed to master - thanks!

**Comment by liamcurry** [comment]
Awesome. Any idea when we'll see a new release on npm?

**Comment by insin** [comment]
Shortly if my toddler will stay asleep. Updating docs and will release as 0.2.0 before tackling #7

**Comment by sdemjanenko** [comment]
Thanks for taking care of this.  It made my week!

**Pull request closed without merging**
